<?php

return [
    'school_name' => env('SCHOOL_NAME', 'Greenfield International School'),
    'academic_year' => env('ACADEMIC_YEAR', '2026-27'),
    'demo_mode' => (bool) env('DEMO_MODE', false),
    'module_descriptions' => [
        'reports' => 'A decision-ready view of academic, attendance and financial health.',
        'users' => 'Manage the people who participate in the learning community.',
        'roles' => 'Review what each stakeholder can see and do.',
        'academics' => 'Classes, sections, capacity and current enrolment.',
        'classes' => 'The classes and learners connected to your teaching load.',
        'subjects' => 'Subject ownership, class context and syllabus completion.',
        'curriculum' => 'Track curriculum units against standards and teaching progress.',
        'timetable' => 'A weekly teaching schedule with periods, rooms and classes.',
        'attendance' => 'Track daily presence, punctuality and trends across the school.',
        'assignments' => 'Create, submit and review meaningful class work.',
        'homework' => 'See open work, deadlines and individual submission status.',
        'submissions' => 'Review submitted work and grading progress.',
        'quizzes' => 'Build knowledge checks and view persisted scores.',
        'question-bank' => 'Reusable questions organised by subject and source quiz.',
        'exams' => 'Upcoming assessments, rooms, duration and marks.',
        'results' => 'Published assessment outcomes by subject.',
        'report-card' => 'A printable overview of the learner’s published performance.',
        'exam-marks' => 'Enter and review marks for the subjects you teach.',
        'performance' => 'Compare learner outcomes across your assigned subjects.',
        'progress' => 'A concise view of achievement across published assessments.',
        'feedback' => 'Actionable, teacher-authored observations for each learner.',
        'behavior' => 'Positive contributions, reminders and resolved classroom notes.',
        'lesson-plans' => 'Teaching objectives, activities and checks for understanding.',
        'content' => 'Learning resources published for the current class.',
        'chapters' => 'Chapter-by-chapter completion across enrolled subjects.',
        'live-classes' => 'Upcoming interactive sessions and joining details.',
        'recordings' => 'Recorded lessons available for revision.',
        'study-materials' => 'Notes, guides and revision resources for every subject.',
        'resources' => 'Your teaching resources, plans and recorded materials.',
        'messages' => 'Private communication with linked school stakeholders.',
        'doubts' => 'Subject questions and teacher responses in one focused inbox.',
        'notices' => 'Keep the school community informed with targeted updates.',
        'library' => 'Current and previous book issues with due-date visibility.',
        'calendar' => 'Academic, cultural and community events in one schedule.',
        'ptm' => 'Confirmed and requested parent-teacher meeting slots.',
        'fees' => 'Offline fee ledger, balances and receipt references. No online checkout.',
        'leave' => 'Submit and review learner or staff absence requests.',
        'documents' => 'Verified school records and administrative requests.',
        'certificates' => 'Achievements and merit certificates issued to the learner.',
        'notifications' => 'Important updates, reminders and recent learner activity.',
        'support' => 'Raise and track help requests with the school office.',
        'settings' => 'Academic policies, grading rules and communication defaults.',
        'audit' => 'A traceable record of important actions in the system.',
        'profile' => 'Account, contact and academic identity details.',
        'child-profile' => 'Academic identity and profile details for the selected learner.',
    ],
    'permissions' => [
        'attendance.manage' => 'Manage attendance',
        'assignments.manage' => 'Create and manage assignments',
        'assignments.submit' => 'Submit and resubmit work',
        'quizzes.manage' => 'Create and manage quizzes',
        'quizzes.attempt' => 'Attempt published quizzes',
        'learning.manage' => 'Manage lesson plans and resources',
        'marks.enter' => 'Enter and update exam marks',
        'feedback.manage' => 'Manage learner feedback and behaviour',
        'notices.manage' => 'Publish class notices',
        'messages.manage' => 'Use approved messaging',
        'leave.manage' => 'Create and cancel leave requests',
        'ptm.manage' => 'Create and reschedule PTM requests',
        'support.manage' => 'Create and update support tickets',
        'documents.manage' => 'Submit requested documents',
        'profile.update' => 'Update own contact profile',
    ],
    'navigation' => [
        'admin' => [
            'Overview' => ['dashboard' => 'Dashboard', 'reports' => 'Reports & analytics'],
            'People' => ['users' => 'User management', 'roles' => 'Roles & permissions'],
            'Academics' => ['academics' => 'Classes & sections', 'subjects' => 'Subjects', 'curriculum' => 'Curriculum', 'timetable' => 'Timetable', 'attendance' => 'Attendance', 'exams' => 'Exams & results'],
            'Operations' => ['notices' => 'Notices', 'fees' => 'Fee records', 'library' => 'Library', 'calendar' => 'Events & calendar', 'leave' => 'Leave requests', 'documents' => 'Documents & certificates'],
            'System' => ['settings' => 'System configuration', 'audit' => 'Audit logs'],
        ],
        'teacher' => [
            'Overview' => ['dashboard' => 'Dashboard', 'classes' => 'My classes', 'timetable' => 'My timetable'],
            'Learning' => ['subjects' => 'Subjects & courses', 'lesson-plans' => 'Lesson plans', 'content' => 'Learning content', 'attendance' => 'Attendance', 'homework' => 'Homework', 'assignments' => 'Assignments', 'submissions' => 'Submission grading', 'quizzes' => 'Quizzes', 'question-bank' => 'Question bank', 'exam-marks' => 'Exam marks'],
            'Engagement' => ['performance' => 'Student performance', 'feedback' => 'Student feedback', 'doubts' => 'Doubts & discussions', 'messages' => 'Parent communication', 'notices' => 'Notices', 'calendar' => 'Calendar', 'resources' => 'Resource library'],
            'Account' => ['profile' => 'My profile'],
        ],
        'student' => [
            'Overview' => ['dashboard' => 'Dashboard', 'subjects' => 'My subjects', 'progress' => 'Learning progress'],
            'Learning' => ['chapters' => 'Courses & chapters', 'content' => 'Learning content', 'live-classes' => 'Live classes', 'recordings' => 'Recorded classes', 'study-materials' => 'Study material', 'homework' => 'Homework', 'assignments' => 'Assignments', 'quizzes' => 'Quizzes'],
            'Academics' => ['exams' => 'Exams', 'results' => 'Results', 'report-card' => 'Report card', 'attendance' => 'Attendance'],
            'Connect' => ['doubts' => 'Doubts & discussions', 'messages' => 'Teacher communication', 'library' => 'Library', 'calendar' => 'Calendar', 'notices' => 'Notices', 'certificates' => 'Certificates'],
            'Account' => ['profile' => 'My profile'],
        ],
        'parent' => [
            'Overview' => ['dashboard' => 'Dashboard', 'child-profile' => 'Child profile', 'progress' => 'Academic progress'],
            'Academics' => ['attendance' => 'Attendance', 'homework' => 'Homework & assignments', 'exams' => 'Exam schedule', 'results' => 'Results & report cards', 'feedback' => 'Teacher feedback', 'behavior' => 'Behaviour & remarks'],
            'Engagement' => ['messages' => 'Teacher communication', 'ptm' => 'Parent-teacher meetings', 'notices' => 'Notices & circulars', 'calendar' => 'Calendar & events'],
            'Administration' => ['fees' => 'Fees & payments', 'leave' => 'Leave requests', 'documents' => 'Documents', 'notifications' => 'Notifications', 'support' => 'Feedback & support'],
            'Account' => ['profile' => 'Parent profile'],
        ],
    ],
];
