<?php

return [
    'products' => [
        'lms' => [
            'name' => 'LMS',
            'eyebrow' => 'Learning ecosystem',
            'description' => 'A connected school operating system for principals, teachers, students, and parents.',
            'icon' => 'graduation-cap',
            'accent' => 'emerald',
            'status' => 'Live',
            'capabilities' => ['Academics', 'Assessment', 'Communication'],
        ],
        'tms' => [
            'name' => 'TMS',
            'eyebrow' => 'Team operations',
            'description' => 'Bring tasks, ownership, priorities, and delivery into one focused workspace.',
            'icon' => 'list-checks',
            'accent' => 'blue',
            'status' => 'Live',
            'capabilities' => ['Planning', 'Workflows', 'Insights'],
        ],
        'sales-crm' => [
            'name' => 'Sales CRM',
            'eyebrow' => 'Revenue intelligence',
            'description' => 'Track leads, daily activity, follow-ups, and conversions in one simple sales workspace.',
            'icon' => 'chart-no-axes-combined',
            'accent' => 'violet',
            'status' => 'Live',
            'url' => '/crm',
            'capabilities' => ['Pipeline', 'Activities', 'Follow-ups'],
        ],
        'google-my-business-contacts-extractor' => [
            'name' => 'Google My Business - Contacts Extractor for Sales Outreach',
            'eyebrow' => 'Sales prospecting',
            'description' => 'Extract structured local-business contacts for targeted sales outreach.',
            'icon' => 'map-pin',
            'accent' => 'amber',
            'status' => 'Live',
            'url' => '/gmb-extractor',
            'capabilities' => ['Discovery', 'Enrichment', 'Export'],
        ],
        'enterprise-rag-system' => [
            'name' => 'Enterprise RAG System with RBAC & Guardrails',
            'eyebrow' => 'Secure knowledge AI',
            'description' => 'Deliver trusted enterprise answers with RBAC, source grounding, and guardrails.',
            'icon' => 'database',
            'accent' => 'rose',
            'status' => 'Live',
            'url' => '/rag',
            'capabilities' => ['RAG', 'RBAC', 'Guardrails'],
        ],
        'website-accessibility-auditor' => [
            'name' => 'Website Accessibility Auditor',
            'eyebrow' => 'Inclusive web quality',
            'description' => 'Audit websites for accessibility issues and turn findings into clear remediation steps.',
            'icon' => 'accessibility',
            'accent' => 'cyan',
            'status' => 'Live',
            'url' => '/accessibility-auditor',
            'capabilities' => ['WCAG', 'Audits', 'Fix guidance'],
        ],
    ],
];
